name: flutter_analyzer
description: A Flutter Analyzer for Flutter Source Code.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-259.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # analyzer: ^0.42.0-nullsafety.0
  analyzer: ^1.0.0
  cupertino_icons: ^1.0.2
  _fe_analyzer_shared: ^16.0.0
  dart_style: 1.3.13
  string_scanner: ^1.1.0
  
dev_dependencies:
  test: ^1.16.2

flutter:
  uses-material-design: true
